### ISSUE TITLE
No handlers could be found for logger "pika.adapters.base_connection"

### ISSUE THREAD

**Issue by markbrough** [pwyf/IATI-Data-Quality#411]
In download_backend and tests_backend, getting the following message (without subprocess):

No handlers could be found for logger "pika.adapters.base_connection"

Still looks like it works...

**Comment by andylolz** [comment]
> It's fine unless there's nothing left in the queue, in which case it stops.

This seems like a separate issue that should also be resolved.

Also, it would be good to specify which exceptions should be caught (rather than using a general `except`). I just mention this because it would make it easier to kill download_backend.py with ^C :)

**Comment by andylolz** [comment]
This doesn’t seem to happen anymore (though I don’t remember fixing it).
