### ISSUE TITLE
Error processing indicator 8 (country strategy) due to IATI schema change

### ISSUE THREAD

**Issue by andylolz** [pwyf/IATI-Data-Quality#453]
I’m hitting an error just here:
https://github.com/pwyf/IATI-Data-Quality/blob/308234e4/iatidq/inforesult_orgtests.py#L200

`.find('title').text` is None because there’s a `<narrative>` element inside `<title>`. This appears to be new in IATI 2.01:
http://iatistandard.org/201/upgrades/integer-upgrade-to-2-01/2-01-changes/#id3
http://iatistandard.org/201/organisation-standard/iati-organisations/iati-organisation/document-link/title/narrative/

`.find('title/narrative').text` would work, but I assume we should still support IATI 1.05?

**Comment by markbrough** [comment]
Yes -- should support both `title/narrative` (2.x) and `title` (1.x)

**Comment by andylolz** [comment]
Gotcha. My lxml is bad – maybe there is some smarter way to do this:

```python
try:
    title = strategy_paper.find('title/narrative').text.upper()
except AttributeError:
    title = strategy_paper.find('title').text.upper()
```

**Comment by andylolz** [comment]
Btw, to what extent does IATI-Data-Quality support 2.01 currently? Are there just some isolated bugs? Is it worth me working through the indicators and checking them against the “what’s new in 2.01” section?

**Comment by markbrough** [comment]
All of the activity-level tests should support 2.01, but I don't think the organisation tests have yet been updated. Not sure the `inforesult_orgtests.py` file has been updated at all so would check that. We need to implement a couple of other changes listed in the [2016 Index consultation](https://github.com/pwyf/2016-index-data-quality-tests/issues), but we don't have to implement them quite yet - can wait a few weeks.

**Comment by andylolz** [comment]
Fix seems to have done the job, so closing this one.
