### ISSUE TITLE
update-frequencies doesn’t take into account org name changes

### ISSUE THREAD

**Issue by andylolz** [pwyf/IATI-Data-Quality#461]
I wonder if this is a problem at the IATI dashboard end… But noting here.

EC, NEAR and EC, DEVCO have both changed name. As far as the IATI dashboard is concerned, though, these are new organisations that have not previously published data, so their publishing frequencies are accordingly ‘annual’. However, if the previous organisation name is factored in, their publishing frequencies are ‘monthly’.

I’ve manually updated these frequencies to monthly. A code solution would require storing a link between the old and new organisation names somewhere.

**Comment by markbrough** [comment]
> However, if the previous organisation name is factored in, their publishing frequencies are 'monthly'.
I agree this makes sense (though note that if we need to re-sync in future, e.g. at the end of data collection, this would get overwritten). Let's also discuss with the IATI Secretariat if there is something that could be adjusted on the IATI Dashboard.

**Comment by andylolz** [comment]
> Let's also discuss with the IATI Secretariat if there is something that could be adjusted on the IATI Dashboard.

@elisedufief is on it :)

> I agree this makes sense (though note that if we need to re-sync in future, e.g. at the end of data collection, this would get overwritten).

Good point, yes.

**Comment by andylolz** [comment]
The nice IATI dashboard people took care of this in the end :rocket:
