### ISSUE TITLE
Incorrect info_result used in summary

### ISSUE THREAD

**Issue by andylolz** [pwyf/IATI-Data-Quality#467]
I’m not exactly sure, but I’m suspicious that this bit of code produces unpredictable results:
https://github.com/pwyf/IATI-Data-Quality/blob/master/iatidq/dqorganisations.py#L393-L394

`_organisation_indicators_inforesults` can return multiple results for an indicator. I guess we want to use the result with the greatest runtime_id. Currently though, we appear to be leaving it up to `update` to choose the result that’s used by the summary.

/cc @markbrough

**Comment by markbrough** [comment]
It shouldn't, because we delete all previous inforesults for a (package, organisation, test) before adding new results:
https://github.com/pwyf/IATI-Data-Quality/blob/master/iatidq/test_queue.py#L395

**Comment by andylolz** [comment]
Aha – I think the problem is that in the instance in question, the organisation package has changed (from `unitedstates-org_state_usaid` to `unitedstates-dosandusaid`).

Is it okay to delete previous inforesults for a (organisation, test) instead? If organisations never have multiple org files, this seems like it should be okay.
